### ISSUE TITLE
音视频通话结束后，APP内其他音频声音会变的很小

### ISSUE THREAD

**Issue by fionaly88** [zhaoyang21cn/iOS_Suixinbo#1]
音视频通话结束后，即使调用 
 [[AVUtil sharedContext] stopContext:^(QAVResult result) {
                [AVUtil destroyShardContext];
            }];
        }];    释放了资源，之后APP 播放 其他音频，声音也会变的很小

我在 1.8 和之前版本的 Demo 里使用系统 AVAudioPlayer 测试过，进入房间前声音正常，进入退出房间之后，播放声音会变得特别小，此时只有退出 APP 才会恢复正常

            NSString *ringSoundFilePath = [[NSBundle mainBundle] pathForResource:@"" ofType:@""];
            NSURL *newURL = [[NSURL alloc] initFileURLWithPath: ringSoundFilePath];
            self.callRingAudioPlyaer = [[AVAudioPlayer alloc] initWithContentsOfURL: newURL error: nil];
            [self.callRingAudioPlyaer play];

**Comment by zhaoyang21cn** [comment]
问题已收到，我们安排专项测试同事进行跟进

**Comment by zhaoyang21cn** [comment]
有没有日志提供，我们可以更快定位

**Comment by JamesChenGithub** [comment]
问题已修改，并上传。原因：退出直播时，未恢复旧的AudioSession状态，已添加此操作

**Comment by fionaly88** [comment]
使用V1.8 IOS 正式版重新测试后发现，该问题依然存在
