### ISSUE TITLE
请问,你们的服务器是不是有点不是很稳定?

### ISSUE THREAD

**Issue by hellerchen** [zhaoyang21cn/iOS_Suixinbo#10]
请问,你们的服务器是不是有点不是很稳定?
下面是我输出的情况
请求视频快的时候能到下面的速度:
[Heller][AV] 成功进入AV Room 总耗时: 0.0853683 (s)
[Heller][AV] 第一帧画面到达 总耗时: 0.229089 (s)

但是慢的时候能到下面的时间,最大能到4秒
[Heller][AV] 成功进入AV Room 总耗时: 0.118945 (s)
[Heller][AV] 第一帧画面到达 总耗时: 1.97409 (s)

下面是接收端的log:
Send[BR=0, Pkt=0, LossRate=0.00%, LossModel=0.00%]    Recv[BR=1209, Pkt=155, LossRate=1.28%, LossModel=30.37%]    RTT=19
UDTSend[LossRate=0.00%, LossModel=0.00%]    UDTRecv[LossRate=0.00%, LossModel=0.00%]

发送端的log:
Send[BR=1056, Pkt=144, LossRate=0.00%, LossModel=0.00%]    Recv[BR=0, Pkt=0, LossRate=0.00%, LossModel=0.00%]    RTT=11
UDTSend[LossRate=0.00%, LossModel=0.00%]    IP[183.57.53.169:8000 IsTCP=0]    AppCPU=25.89%  SYSCPU=30.00%SDKVersion=1.8.1.222(25231582)

我们基本排除网络造成的问题,因为相同光钎网络下,映客视频到达的时间都是很快的,映客用的就是你们服务吧?

**Comment by zhaoyang21cn** [comment]
我们找到了一个会引起进入房间慢的bug，第一个视频帧在某些情况下出现异常
我们本周修复该bug

**Comment by hellerchen** [comment]
@zhaoyang21cn 感谢回复
