### ISSUE TITLE
直播几个小时,观众端会莫名的看不到画面,但是还能听到声音

### ISSUE THREAD

**Issue by hellerchen** [zhaoyang21cn/iOS_Suixinbo#13]
直播几个小时后,视频会停止发送,但是在观众端还能听到声音,主播端也能正常的收到用户进出房间的通知,但是通过旁路直播分享的hls地址还能看到主播的画面...

我把视频,音频,公共部分的tips输出发现已经没有视频部分下发的log:
公共部分:
	
	Send[BR=538, Pkt=95, LossRate=0.00%, LossModel=0.00%]    Recv[BR=0, Pkt=0, LossRate=0.00%, LossModel=0.00%]    RTT=19
	
	UDTSend[LossRate=0.00%, LossModel=0.00%]    UDTRecv[LossRate=0.00%, LossModel=0.00%]
	
	IP[14.17.44.45:8000 IsTCP=0]    AppCPU=32.00%  SYSCPU=45.38%SDKVersion=1.8.1.222(25231582)
	
	音频部分:
	
	编解码[Qua=0, QuaValid=0, RealPkg=10, TotalPkg=10, PkgRate=100.00%, LossCnt=0, Flow=0, Jitter=3344]
	
	流控下发[CodecType=4106, SampleRate=48000, BR=64000, PackMS=40, NM=6+0, MTU=0, INFEC=0, JC=0[0,0], DS=0]
	
	V:11532 M:1 _ T:29345s
	AEC :ON  I:48000,1 F:48000,2 O:48000,2
	AGC :ON  G:15.5dB N:-52.0dB M:15.5dB E:-11.8dB
	NS  :ON 
	VAD :OFF
	MIX :    48000,2
	CAP :    hw:-1,-1 sr:48000,1
	         217,232,15631,7196,535
	PLAY:    hw:-1,-1 sr:48000,2
	         0,0,0,0,0
	ENC :    AAC 48000,2 B:64000
	其他[AudioCategory=1]

Jun  2 20:14:20  Live[1395] <Warning>: landy trae kVTEncodeFrameOptionKey_ForceKeyFrame !!!  
Jun  2 20:14:21  kernel[0] <Notice>: VXE380 ERROR: F 215800 PTSdiff = 0 -> default to previous fps 180

**Comment by JamesChenGithub** [comment]
demo 里面使用AudioCategory的是CATEGORY_VOICECHAT （0）

**Comment by hellerchen** [comment]
@JamesChenGithub 你好,我是看你们接口说明改动的,所以说另外两种模式其实有问题?
  /// VoIP模式，适合于实时音频通信场景，如实时语音通话。
  CATEGORY_VOICECHAT = 0,

  ///媒体采集与播放模式，适合于那些对音质要求比较高的直播场景，如主播场景中的主播人员。
  CATEGORY_MEDIA_PLAY_AND_RECORD = 1,

  ///媒体播放模式，适合于那些对音质要求比较高的直播场景，如主播场景中的听众。
  CATEGORY_MEDIA_PLAYBACK = 2,

**Comment by JamesChenGithub** [comment]
更新SDK后是否，是否还有该问题？

**Comment by JamesChenGithub** [comment]
更新SDK后是否，是否还有该问题？另外你代码的backgroundmode设置的是什么？

**Comment by hellerchen** [comment]
@JamesChenGithub UIBackgroundmodes 是 audio

**Comment by JamesChenGithub** [comment]
更新下代码，现在默认退后台，有后台模式，会关掉Mic
