### ISSUE TITLE
1.8.1SDK 退出房间 crash

### ISSUE THREAD

**Issue by huize** [zhaoyang21cn/iOS_Suixinbo#15]
我们线上产品收集到的crash,看堆栈应该是退出房间的时候crash的,以下是crash信息的地址,麻烦看看.
http://bugly.qq.com/share/koA5uu

**Comment by JamesChenGithub** [comment]
非Demo的问题：issue上提的问题尽量是用demo重现出来的，这样才好修复。建意参考demo以及文档退房间流程
