### ISSUE TITLE
iOS 经常闪屏，后台配置问题吗？推荐配置是20fps，我看其他问题说又要改成15fps？到底怎么处理，改了还是闪

### ISSUE THREAD

**Issue by unknowntc** [zhaoyang21cn/iOS_Suixinbo#18]

**Comment by JamesChenGithub** [comment]
看下最下的readme下的配置，

**Comment by zhaotianci** [comment]
readme   写的是20fps,但是我看到其他issues 里面写闪是要改成15fps？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by JamesChenGithub** [comment]
没太明白你指的闪屏，具体现象是什么样的，我所说的改成640*480 15fps，只会影响进入房间后差不多隔三秒会闪一下。如果不是这个，麻烦录一个视频看下现象

**Comment by JamesChenGithub** [comment]
使用最新的AVSDK 1.8.1.300试一下

**Comment by Chakery** [comment]
@unknowntc 

请问你的闪屏问题解决了么？
