### ISSUE TITLE
疑似互动直播摄像头bug

### ISSUE THREAD

**Issue by wangziUSTC** [zhaoyang21cn/iOS_Suixinbo#2]
ios－sdk版本为1.8.1.219
随心播的代码中，所有enableCamera的地方，使用的都是“CameraPosFront”参数进行开关摄像头工作（无论当前是前置摄像头还是后置摄像头），然后如果是后置摄像头的情况下关闭了，然后再打开的时候，虽然是“CameraPosFront”，但是实际上打开的是后置摄像头。此时切换摄像头的操作是好的。

如下一种情况会出现切换摄像头失败（报错QAV_ERR_HAS_IN_THE_STATE）：
1、首次enableCamera的时候使用参数“ CameraPosFront”，此时打开成功
2、然后切换几次摄像头，停留在后置摄像头
3、因为此时是后置摄像头，所以我理所应当的在enableCamera No的时候，使用参数“ CameraPosBack”，关闭成功
4、又需要打开摄像头，此时再用“ CameraPosFront”打开，但是此时打开的是后置摄像头（和demo类似）
5、但是此时switchCamera就失败了，返回错误码：1003（QAV_ERR_HAS_IN_THE_STATE）

**Comment by JamesChenGithub** [comment]
后续用demo重现下，最近在忙开发，后续跟进

**Comment by JamesChenGithub** [comment]
请更新下，切换时候不会，关闭是的摄像头要与当前的AVSDK底层的一致。demo是有记住摄像头的id，上层使用时只需要指定初始时的值即可。
