### ISSUE TITLE
1.8.1 SDK 对方退到后台再回来 就看不到对方画面了,请问这个怎么解决?

### ISSUE THREAD

**Issue by c344081** [zhaoyang21cn/iOS_Suixinbo#20]
1.8.1 SDK 对方退到后台再回来 就看不到对方画面了,退出房间再进就会提示请求主播画面失败,然后就退出去了
补充一下:  - OnVideoPreview: 这个时候没有回调...

**Comment by JamesChenGithub** [comment]
退后台会关摄像头，没有上行的视频，所以看不到，是正常的。具体操作业务逻辑上去处理

**Comment by c344081** [comment]
退到后台后右回到前台了,有开摄像头的操作
