### ISSUE TITLE
关于视频显示

### ISSUE THREAD

**Issue by ewcfengye** [zhaoyang21cn/iOS_Suixinbo#21]
原来SDK1.3的那个context.videoCtrl getPreviewLayer 在1.8不能使用，
在使用这个互动直播的demo的时候，里面的TCAVMultiLivePreview 大小无法随意的改变，一改变大小就有可能导致视图无法显示

然后我采用- (void)OnLocalVideoPreview:(QAVVideoFrame *)frameData 返回的YUV数据直接进行解析
图像是黑白的，能否帮我看一下 哪里的参数错误 代码在doc中
[YUV解析视图.docx](https://github.com/zhaoyang21cn/iOS_Suixinbo/files/313086/YUV.docx)

**Comment by zhaoyang21cn** [comment]
建议使用avsdk1.8.1最新版本
