### ISSUE TITLE
发布直播遇到问题,急需帮助

### ISSUE THREAD

**Issue by Waitwalker** [zhaoyang21cn/iOS_Suixinbo#22]
appDelegate的继承逻辑应该处理好了,也能登录,能正常获取直播列表,点击也能观看直播.
我把demo中的PublishLiveViewController类直接拖到自己app里面,然后点击一个按钮push这个类,就报这样的错误[IMAHost showLocation]: unrecognized selector sent to instance 0x12d909ce0,报错位置在PublishLiveViewController类
![2](https://cloud.githubusercontent.com/assets/16695783/16066751/829ab444-32e8-11e6-8e87-75e280a6d909.jpg)

输出:
![1](https://cloud.githubusercontent.com/assets/16695783/16066759/99a38648-32e8-11e6-86f0-e0d59992a015.jpg)

demo中的位置打断点输出:
![3](https://cloud.githubusercontent.com/assets/16695783/16066768/aebd63d2-32e8-11e6-9e5d-fcd13181da45.jpg)

求解决!!!!!!

**Comment by JamesChenGithub** [comment]
// 配置自定义的_host，hostcls须为IMAHost的子类
+ (void)configHostClass:(Class)hostcls;
