### ISSUE TITLE
对方从后台回到前台之后就看不到对方画面了...

### ISSUE THREAD

**Issue by c344081** [zhaoyang21cn/iOS_Suixinbo#23]
#### SDK 1.8.1 对方从后台回到前台之后就看不到对方画面
- 对方回到前台的时候有重新打开摄像头,
- 我也有去请求对方画面
- DEMO里面如果是主播在视频状态从后台回到前台,那么在这个操作之后进直播间的观众都会因为请求主播画面失败而退出房间
- 主播从后台回到前台之后观众端的 ``` - onVideoPreview: ```  没有回调

**Comment by JamesChenGithub** [comment]
目前正在修复

**Comment by JamesChenGithub** [comment]
更新Git，使用最新版本试试
