### ISSUE TITLE
后续考虑支持重力感应么

### ISSUE THREAD

**Issue by WzoneLayer** [zhaoyang21cn/iOS_Suixinbo#28]
请问，咱们的程序后续考虑支持重力感应么？

**Comment by zhaoyang21cn** [comment]
根据手机的状态进行横屏展示，这个已经可以做，但是有些黑边问题需要业务处理

**Comment by JamesChenGithub** [comment]
是否是要做全屏显示？或横习显示？参考下TCAVIMDemo--->全屏显示FullLivePreview
