### ISSUE TITLE
SDK1.8.1 闪退

### ISSUE THREAD

**Issue by yingqiangh** [zhaoyang21cn/iOS_Suixinbo#29]
友盟上跟踪到崩溃日志：
Application received signal SIGABRT
(null)
((
	0   CoreFoundation                      0x000000018342edc8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000182a93f80 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018342ecf8 <redacted> + 0
	3   ZhiBo                               0x10094bf10 _ZN7tencent2av22__internal_new_creatorINS_2im2cs8longconn7putinfo11TransBufferEEEPvv + 5592376
	4   ZhiBo                               0x100b27cd8 _ZN7tencent2av22__internal_new_creatorINS_2im2cs8longconn7putinfo11TransBufferEEEPvv + 7541504
	5   libsystem_platform.dylib            0x000000018308d94c _sigtramp + 68
	6   libsystem_pthread.dylib             0x0000000183094ef8 pthread_kill + 112
	7   libsystem_c.dylib                   0x0000000182f39dac abort + 140
	8   libsystem_malloc.dylib              0x0000000182ff4374 <redacted> + 0
	9   ZhiBo                               0x1002a3304 _ZN5xpstl3mapIijE11rotateRightEPNS1_6RBTreeIijEE + 1275892
	10  ZhiBo                               0x10044628c _ZN7tencent2av22__internal_new_creatorINS_2im2cs8longconn7putinfo11TransBufferEEEPvv + 325812
	11  ZhiBo                               0x10042287c _ZN7tencent2av22__internal_new_creatorINS_2im2cs8longconn7putinfo11TransBufferEEEPvv + 179876
	12  ZhiBo                               0x10042d10c _ZN7tencent2av22__internal_new_creatorINS_2im2cs8longconn7putinfo11TransBufferEEEPvv + 223028
	13  ZhiBo                               0x10040351c _ZN7tencent2av22__internal_new_creatorINS_2im2cs8longconn7putinfo11TransBufferEEEPvv + 52036
	14  ZhiBo                               0x100439444 _ZN7tencent2av22__internal_new_creatorINS_2im2cs8longconn7putinfo11TransBufferEEEPvv + 273004
	15  ZhiBo                               0x1003fb848 _ZN7tencent2av22__internal_new_creatorINS_2im2cs8longconn7putinfo11TransBufferEEEPvv + 20080
	16  ZhiBo                               0x1002c1b20 _ZN5xpstl3mapIijE11rotateRightEPNS1_6RBTreeIijEE + 1400848
	17  ZhiBo                               0x1002c1c94 _ZN5xpstl3mapIijE11rotateRightEPNS1_6RBTreeIijEE + 1401220
	18  ZhiBo                               0x1002ba0b0 _ZN5xpstl3mapIijE11rotateRightEPNS1_6RBTreeIijEE + 1369504
	19  libsystem_pthread.dylib             0x0000000183093b28 <redacted> + 156
	20  libsystem_pthread.dylib             0x0000000183093a8c <redacted> + 0
	21  libsystem_pthread.dylib             0x0000000183091028 thread_start + 4
)

dSYM UUID: 81CD3955-B00C-3C52-802D-04B4DA368FC3
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: ZhiBo
Base Address: 0x00000001000dc000

用crash tool 定位到的大概的代码位置如下：
UmengSignalHandler (in ZhiBo) + 128
rqd_signal_handler(int, __siginfo*, void*) (in ZhiBo) + 1860
tag_st_obj::Release() (in ZhiBo) (biclss.cpp:79)
CAVGUdtSend::UDTSaveRawData(unsigned char*, unsigned int, unsigned int, unsigned char) (in ZhiBo) (AVGUDT.cpp:1663)
CAVGCsProcessor::SendStream(unsigned char const*, unsigned int, unsigned char) (in ZhiBo) (AVGCsProcessor.cpp:462)
CAVGRoomLogic::SendStream(unsigned char const*, unsigned int, unsigned char) (in ZhiBo) (AVGRoomLogic.cpp:1664)
CAVGRoomLogicProxy::SendStream(unsigned char const*, unsigned int, unsigned char) (in ZhiBo) (AVGRoomLogicProxy.cpp:208)
non-virtual thunk to CAVGSession::OnMESendStreamData(unsigned char*, unsigned int) (in ZhiBo) (AVGSession.cpp:346)
CNetWorkSinkImp::SendNetPacket(unsigned char*, int, int) (in ZhiBo) (AudioEngCtrl.cpp:74)
CNetSink::SysThreadProc() (in ZhiBo) + 676
non-virtual thunk to CNetSink::SysThreadProc() (in ZhiBo) + 16
CSysThread::GSysThreadProc(void*) (in ZhiBo) + 60

**Comment by JamesChenGithub** [comment]
请填写重现步骤

**Comment by yingqiangh** [comment]
不好重现，频率很低，不知道什么时候发生！

**Comment by JamesChenGithub** [comment]
已反馈给SDK同事。待新版本1.8.2中进行验证
