### ISSUE TITLE
主播断开网络，再打开网络。直播无法继续

### ISSUE THREAD

**Issue by yingqiangh** [zhaoyang21cn/iOS_Suixinbo#30]
主播断开网络，再打开网络。直播无法继续。
在直播间的观众收不到新画面。
其他观众无法进入，提示“请求画面超时”
不是必现

**Comment by JamesChenGithub** [comment]
问题已记录，呆修复后回复

**Comment by JamesChenGithub** [comment]
观众可以在onvideoPreview里面加监听，超过一定时间无数据返回，可认为主播离开，主播断网的过程中，加入的观众会请求不到画面，这块的处理，可根据你们自己app的逻辑进行调整，

**Comment by JamesChenGithub** [comment]
已添加相应的处理逻辑，请更新代码进行验证
