### ISSUE TITLE
随心播 主播变成飞行模式 偶尔崩溃

### ISSUE THREAD

**Issue by yingqiangh** [zhaoyang21cn/iOS_Suixinbo#31]
详见附件截图
![12223](https://cloud.githubusercontent.com/assets/11433539/16333133/379c0c9a-3a2c-11e6-8df1-2f90878bdeca.png)

**Comment by JamesChenGithub** [comment]
问题已记录，后续版本进行修复

**Comment by zhaoyang21cn** [comment]
麻烦用最新1.8.2验证一下
