### ISSUE TITLE
根据音频透传文档变声操作无效

### ISSUE THREAD

**Issue by xiaoyu5062** [zhaoyang21cn/iOS_Suixinbo#32]
ios端变声如何操作呢？
我看的《混音透传自定义音效使用说明-jeringzhu-2016-05-05.pdf》中的操作，但是文档可能是针对安卓的。
我目前的操作是
 注册回调：QAVAudioCtrl  registerAudioDataCallback  并设置了委托， 
然后有三个回调，只有这个会执行-
 (QAVResult)audioDataDispose:(QAVAudioFrame*)audioFrame type:(QAVAudioDataSourceType)type ，我是直接在这里面用SoundTouch对audioFrame的buffer进行处理.
具体代码如下：
- (QAVResult)audioDataDispose:(QAVAudioFrame*)audioFrame  type:(QAVAudioDataSourceType)type{
    if (type==QAVAudioDataSource_VoiceDispose) {

        audioFrame.buffer= [SoundTouchObj updataAudioSampleRate:0 tempoChangeValue:0 pitchSemiTones:12 rateChange:0 data:audioFrame.buffer];//此方法为处理变声数据
//是否需要把处理后的buffer赋值给audioFrame.buffer??
//另外处理之前的buffer长度与处理后的长度也不一样，这个有没有影响？
    }
    return QAV_OK;
}

**Comment by jming0618** [comment]
我处理方式跟你一样，也是变不了声。。

**Comment by wbzlop** [comment]
啊。一样。处理后的数据保存下来后播放，确实已经变声了，但是赋给audioFrame.buffer完全无效。在QAVAudioDataSource_Send回调的数据是原始数据。也就是说发送出了原始数据......

**Comment by xiaoyu5062** [comment]
有没有人解决这个问题的？？

**Comment by JamesChenGithub** [comment]
audioFrame.buffer= [SoundTouchObj updataAudioSampleRate:0 tempoChangeValue:0 pitchSemiTones:12 rateChange:0 data:audioFrame.buffer];//此方法为处理变声数据   ----->此处有问题。

audioFrame是底层分配出来的，底层处理的是 const void *btyes =［audioFrame.buffer bytes］，btyes不能修改，上面的直接赋值会修改btyes指针，建议处理完数据后，再copy回到btyes内部：

**Comment by JamesChenGithub** [comment]
另添加相应的处理方式
-(QAVResult)audioDataDispose:(QAVAudioFrame*)audioFrame type:(QAVAudioDataSourceType)type
{
// 总原则，不修改audioFrame.buffer.bytes所指向的内容
    if (type==QAVAudioDataSource_VoiceDispose)
    {
        void* p = (void*)audioFrame.buffer.bytes;
        for(NSUInteger n=0; n<[audioFrame.buffer length]; n+=sizeof(short))
        {
            p += n;
            short* pv = (short*)p;
            (*pv) /= 4;
        }
    }
    return QAV_OK;
}

**Comment by xiaoyu5062** [comment]
这段代码是什么作用？？？
for(NSUInteger n=0; n<[audioFrame.buffer length]; n+=sizeof(short))
{
p += n;
short pv = (short)p;
(pv) /= 4;
}

**Comment by JamesChenGithub** [comment]
这段代码是什么作用？？？
for(NSUInteger n=0; n<[audioFrame.buffer length]; n+=sizeof(short))
{
p += n;
short pv = (short)p;
(pv) /= 4;
}
