### ISSUE TITLE
kIsUseAVSDKAsLiveScene 这个值设为1，只要闪退后，之后就进不去房间了，一直报10001，后台错误码是71，用户id错误，我现在一直用的0，随机闪退

### ISSUE THREAD

**Issue by unknowntc** [zhaoyang21cn/iOS_Suixinbo#34]

**Comment by JamesChenGithub** [comment]
kIsUseAVSDKAsLiveScene 一直设为 0 不要去修改他，随机闪退（重点检查下是否有内存释放），你用同样的操作（非Debug），对比Demo以及你的App，如果demo也有问题，提供下相关日志，如果是你的App，对比下Demo逻辑

**Comment by unknowntc** [comment]
什么都是比对deme？？？，我们又不是你们的测试，是你们帮我们解决问题
