### ISSUE TITLE
iOS 随心播demo中与互动观众互动成功后，观众说话，主播听不到只能看到观众画面

### ISSUE THREAD

**Issue by mrpompy** [zhaoyang21cn/iOS_Suixinbo#37]
iOS 随心播demo中与互动观众互动成功后，观众说话，主播听不到只能看到观众画面，而主播说话观众听的到

**Comment by guangmingzizai** [comment]
请看#36，前两天也遇到这个问题，好坑呀！
QQ：632458941

**Comment by JamesChenGithub** [comment]
更新下最新的SDK进行验证。另外检查角色与权限相关的配置逻辑

**Comment by mrpompy** [comment]
用的是你的TCShowDemo  难道你们 role的名称更改了  不是InteractUser 了吗
