### ISSUE TITLE
视频通话过程中，自己手动断开网络直到超时，腾讯AV库崩溃

### ISSUE THREAD

**Issue by fionaly88** [zhaoyang21cn/iOS_Suixinbo#4]
附件里提供了崩溃堆栈截图，APP内日志，以及控制台输出的日志

[日志.zip](https://github.com/zhaoyang21cn/iOS_Suixinbo/files/279101/default.zip)

**Comment by JamesChenGithub** [comment]
麻烦先使用demo测试同样的操作看会不会出现，如果Demo没有对比demo与你app调用的AVSDK的顺序，对比demo以及文档检查你app的逻辑

**Comment by JamesChenGithub** [comment]
确认下你代码里面是不是有内存泄露导致引用AVSDK相关的没释放掉
