### ISSUE TITLE
其中一方进入后台有一分钟左右，再进入前台   ，对方看到的画面是卡住的，即 对方看不到  退出后台再回来一方的画面。

### ISSUE THREAD

**Issue by hugo-** [zhaoyang21cn/iOS_Suixinbo#43]

**Comment by hugo-** [comment]
打log看   进入后台再回来的一方 isCameraOn是NO ，进入后台再回来自己的摄像头就关了SDK AV1.8

**Comment by JamesChenGithub** [comment]
主播退后台，关Camera不再上行数据，进前台后，再打开camera上行视频数据。
你的问题应该是：主播再回前台时，观众端的画面是否有更新。
更新下代码，现已支持主播退后台通知，观众端会显示主播离开消息

**Comment by hugo-** [comment]
互动直播，主播端回前台后 观众端无更新   OnVideoPreview回调不再走，重新requestView  却报参数错误

**Comment by hugo-** [comment]
现在已是最新代码，我们现在场景是  两方视频聊天，其中一方进后台后  过段时间回前台  其中一方视频画面无更新  会卡住 不走OnVideoPreview回调，  进后台后立马回前台是可以恢复的，在后台呆段时间再回来就不能恢复了
