### ISSUE TITLE
伴奏问题

### ISSUE THREAD

**Issue by xiaoyu5062** [zhaoyang21cn/iOS_Suixinbo#44]
以前iOS 1.6的SDK开直播的时候主播打开QQ音乐或者其它播放器放歌，观众那一端不用处理就能听到，到1.7之后好像就都不可以了，是内部屏蔽了还是这个是有什么地方配置的吗？
如果采用混音透传的方式，sdk有方法直接把当前扬声器播放的20ms的数据给我吗？不能的话我是直播用伴奏的音频文件取20ms合到混音透传的回调接口里？

**Comment by JamesChenGithub** [comment]
以前iOS 1.6的SDK开直播的时候主播打开QQ音乐或者其它播放器放歌，观众那一端不用处理就能听到，到1.7之后好像就都不可以了，是内部屏蔽了还是这个是有什么地方配置的吗？--->1.7以后，代码里面将音频模式抢了，不抢会导致app无法录音；

**Comment by JamesChenGithub** [comment]
如果采用混音透传的方式，sdk有方法直接把当前扬声器播放的20ms的数据给我吗？不能的话我是直播用伴奏的音频文件取20ms合到混音透传的回调接口里？－－－> TCAVIMDemo里面有提透传示例

**Comment by jianhualee** [comment]
TCAVIMDemo里面有提透传示例  ->确定是在这个项目里吗？我怎么没找到，谢谢

**Comment by JamesChenGithub** [comment]
音频透传，五笔打错了不好意思

**Comment by jianhualee** [comment]
在TCAVIMDemo 工程中，我没有找到 任何调用 registerAudioDataCallback 的代码，请问您说的音频透传示例在哪呢，谢谢

**Comment by jianhualee** [comment]
我想做音效，和背景音乐播放，请问能给个思路不，比如如何处理NSData数据等等，谢谢

**Comment by jianhualee** [comment]
您能把音频透传 代码片段上传一下吗？谢谢

**Comment by jianhualee** [comment]
我试了一下，发现micAudioTransmissionData 的注视是：Mic透传数据:开Mic端配置，自己听到，其他人可听到。但是实际测试发现,自己听不到，其他人可以听到。如果要实现伴奏的功能，需要同时开启startMicAudioTransmission 与startSpeakerAudioTransmission 。
