### ISSUE TITLE
主播退到后台，然后主播重新进入，观众界面卡死

### ISSUE THREAD

**Issue by choiceyou** [zhaoyang21cn/iOS_Suixinbo#45]
AV_iOS_SDK1.8.1.1 主播退到后台，然后主播重新进入，观众界面卡死（可能直播间被销毁了），最新的随心播demo也会出现这样的问题，希望您们能跟进下，谢谢。。。

**Comment by JamesChenGithub** [comment]
主播退后台，不会继续上行视频，超90S，后台自动解散房间。观众界面的卡死是指什么？画面不动？还是界面上的按钮不能操作？面面不动：是因为没有上行，只显示到最后一帧，是正常逻辑；按钮不能点击：建议查看自身app逻辑。
