### ISSUE TITLE
IOS互动直播怎么配置spear都是噪点太严重

### ISSUE THREAD

**Issue by huakucha** [zhaoyang21cn/iOS_Suixinbo#47]
对比映客和NOW 都是你们的产品为什么视频看着就很舒服 自己接入SDK噪点多得无法接受

**Comment by JamesChenGithub** [comment]
不太明白具体问题是什么？我用两个手机进NOW直播与观看，两个手机靠得很近的时候，会有噪声？是这个吗？如果是这种情况：mic跟speaker靠得很近的时候会产生啸叫，这个是物理现象。如果是开发测试时，建议把kAVSDKDefaultOpenMic 改为 0

**Comment by JamesChenGithub** [comment]
建议参考ReadMe中的配置
