### ISSUE TITLE
编译tvshow target报错

### ISSUE THREAD

**Issue by laoyao** [zhaoyang21cn/iOS_Suixinbo#48]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IMUserId", referenced from:
      objc-class-ref in QAVSDK(IMChannelImpl.o)
  "_OBJC_CLASS_$_AVMultiInviteUser", referenced from:
      objc-class-ref in IMCore(TIMInnerAVInviteCallback.o)
  "tencent::im::im_service::msg_subtype_0x32::MsgBody::MsgBody()", referenced from:
      -[TIMInnerAVInviteCallback onAvInviteBuf:] in IMCore(TIMInnerAVInviteCallback.o)
  "tencent::im::im_service::msg_subtype_0x32::MsgBody::default_instance_", referenced from:
      -[TIMInnerAVInviteCallback onAvInviteBuf:] in IMCore(TIMInnerAVInviteCallback.o)
  "tencent::im::im_service::msg_subtype_0x32::UserInfo::UserInfo(tencent::im::im_service::msg_subtype_0x32::UserInfo const&)", referenced from:
      -[TIMInnerAVInviteCallback onAvInviteBuf:] in IMCore(TIMInnerAVInviteCallback.o)
  "tencent::im::im_service::msg_subtype_0x32::UserInfo::~UserInfo()", referenced from:
      -[TIMInnerAVInviteCallback onAvInviteBuf:] in IMCore(TIMInnerAVInviteCallback.o)
  "tencent::im::im_service::msg_subtype_0x32::MsgBody::~MsgBody()", referenced from:
      -[TIMInnerAVInviteCallback onAvInviteBuf:] in IMCore(TIMInnerAVInviteCallback.o)
  "_OBJC_CLASS_$_TIMCodingModel", referenced from:
      _OBJC_CLASS_$_TIMAddFriendRequest in IMCore(TIMFriendshipManager.o)
      _OBJC_CLASS_$_TIMFriendMetaInfo in IMCore(TIMFriendshipManager.o)
      _OBJC_CLASS_$_TIMUserProfile in IMCore(TIMFriendshipManager.o)
      _OBJC_CLASS_$_TIMFriendPendencyItem in IMCore(TIMFriendshipManager.o)
      _OBJC_CLASS_$_TIMFriendFutureMeta in IMCore(TIMFriendshipManager.o)
      _OBJC_CLASS_$_TIMFriendFutureItem in IMCore(TIMFriendshipManager.o)
      _OBJC_CLASS_$_TIMFriendPendencyMeta in IMCore(TIMFriendshipManager.o)
      ...
  "_OBJC_CLASS_$_TIMInnerRequest", referenced from:
      objc-class-ref in IMCore(IMCoreImpl.o)
  "_OBJC_CLASS_$_AVRecordInfo", referenced from:
      objc-class-ref in TCAVLiveRoomEngine+Record.o
  "_OBJC_CLASS_$_TIMGlobalConfig", referenced from:
      objc-class-ref in IMCore(IMCoreImpl.o)
  "_OBJC_CLASS_$_AVMultiInvitationReq", referenced from:
      objc-class-ref in IMCore(TIMInnerAVInviteCallback.o)
  "_OBJC_CLASS_$_LVBChannelInfo", referenced from:
      objc-class-ref in TCAVLiveRoomEngine+PushStream.o
  "_OBJC_CLASS_$_TIMInnerQuality", referenced from:
      objc-class-ref in IMCore(IMCoreImpl.o)
  "_OBJC_METACLASS_$_TIMLoginParam", referenced from:
      _OBJC_METACLASS_$_IMALoginParam in IMALoginParam.o
  "_OBJC_CLASS_$_OMCustomLogger", referenced from:
      objc-class-ref in IMCore(IMCoreImpl.o)
  "_OBJC_CLASS_$_AVStreamInfo", referenced from:
      objc-class-ref in TCAVLiveRoomEngine+PushStream.o
  "_OBJC_METACLASS_$_TIMCodingModel", referenced from:
      _OBJC_METACLASS_$_TIMUserProfile in IMCore(TIMFriendshipManager.o)
      _OBJC_METACLASS_$_TIMAddFriendRequest in IMCore(TIMFriendshipManager.o)
      _OBJC_METACLASS_$_TIMFriendMetaInfo in IMCore(TIMFriendshipManager.o)
      _OBJC_METACLASS_$_TIMFriendPendencyItem in IMCore(TIMFriendshipManager.o)
      _OBJC_METACLASS_$_TIMFriendFutureMeta in IMCore(TIMFriendshipManager.o)
      _OBJC_METACLASS_$_TIMFriendFutureItem in IMCore(TIMFriendshipManager.o)
      _OBJC_METACLASS_$_TIMFriendPendencyMeta in IMCore(TIMFriendshipManager.o)
      ...
  "_OBJC_CLASS_$_OMAVRoomInfo", referenced from:
      objc-class-ref in TCAVLiveRoomEngine+Record.o
  "_OBJC_CLASS_$_IMSdkInt", referenced from:
      objc-class-ref in IMAPlatform+Login.o
  "_OBJC_CLASS_$_TIMLoginParam", referenced from:
      l_OBJC_$_CATEGORY_TIMLoginParam_$_PlatformConfig in IMALoginParam.o
      _OBJC_CLASS_$_IMALoginParam in IMALoginParam.o
  "_OBJC_CLASS_$_TIMManager", referenced from:
      objc-class-ref in IMAPlatform+Login.o
     (maybe you meant: _OBJC_CLASS_$_TIMManagerImpl)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="1381" alt="2016-07-20 6 46 35" src="https://cloud.githubusercontent.com/assets/870777/16983976/52b14260-4eaa-11e6-9152-db6e41c3cb22.png">

**Comment by JamesChenGithub** [comment]
是否导入IMSDK+AVSDK，建议先阅读ReadMe说明：因GitHub有文件大小限制，现将IMSDK以及AVSDK上传到腾讯云COS上。 更新时，请到对应的地址进行更新，并添加到工程下面对应的目录下

IMSDK : http://tcshowsdks-10022853.cos.myqcloud.com/20160629/IMSDK.zip 下载后解压，然后再放至对应放到工程目录 TCShow/TCAdapter/TIMAdapter/Framework/IMSDK

AVSDK : http://tcshowsdks-10022853.cos.myqcloud.com/20160629/Libs.zip 下载后解压，然后再放至对应放到工程目录 TCShow/TCAdapter/TCAVIMAdapter/Libs
