### ISSUE TITLE
登录的UI在项目中找不见

### ISSUE THREAD

**Issue by iStig** [zhaoyang21cn/iOS_Suixinbo#51]
target:TCShow
file:IMALoginViewController.m
代码行号: 181       _tlsuiwx = TLSUILogin(self, setting);

对他的描述是以下
/*! @brief 拉起TLSUI登录框
 *
 * @param vc 当前view controller 需要实现TLSUILoginListener接口
 * @param setting 登录框设置
 * @return 回调对象，目前用于微信、微博登录回调
 */
FOUNDATION_EXPORT id TLSUILogin(UIViewController<TLSUILoginListener> *vc, TLSUILoginSetting *setting);

不太清楚这是怎么调用登录的ui的。可否指点迷津

**Comment by iStig** [comment]
大致了解了   其实这个ui应该是配置在sdk中的吧

**Comment by zhaoyang21cn** [comment]
TLSUI.framework中的，//进入登录界面
- (void)enterLoginUI;
