### ISSUE TITLE
这个app集成的短信验证登录是不是托管模式   而手动输入用户名密码是否是独立模式

### ISSUE THREAD

**Issue by iStig** [zhaoyang21cn/iOS_Suixinbo#54]
目前我想集成独立模式 但是总是无法走通以下登录回调

  TIMLoginParam *param = [[TIMLoginParam alloc] init];
  param.identifier =  @"xudong";//自己服务器的用户帐号名
  param.accountType = @"5562";//平台上的accountType
  param.userSig =  [self readFileName:@"sig"];//userSig是写死在本地,这是服务器获取对应账号"xudong"的usersig
  param.sdkAppId = 1400009808;//平台上的accountType
  param.appidAt3rd = @"1400009808";//根据文档独立模式保持跟sdkAppId一致
  [[TIMManager sharedInstance] login:param succ:^{

  } fail:^(int code, NSString *msg) {
    
  }];

控制台也没有信息提供
![7cacec38-711f-4500-8b08-0ded40006bf8](https://cloud.githubusercontent.com/assets/2696927/17804568/cbf611aa-662e-11e6-96f5-92c05d664053.png)

以上这是我的测试调试接口 ,不清楚是否有遗漏什么东西导致没办法请求成功

**Comment by JamesChenGithub** [comment]
登录只前是否有initSDK？具体问题可以到IM群里面去问题一下
