### ISSUE TITLE
在直播结束页将随心播切换至后台，再切回来，再进入直播崩溃问题

### ISSUE THREAD

**Issue by hnzlk2014** [zhaoyang21cn/iOS_Suixinbo#55]
复现步骤：
1.进入直播，再点击退出，显示结束页浮层。
2.切换APP到后台，再回来，点返回。（这个时个估计没有释放，如果没切到后台没问题）
3.再次进入互动直播，会显示红屏，再退出来，到列表页，就会崩溃。

环境：
随心播最新的代码，旧代码和新代码都有问题，SDK也是最新的，ios9.3.2,xcode7.3.1

因为我们在直播结束页有分享的逻辑，会切换出去，故发现了此bug。

比较急，临近发版，还望能给出修复建议，谢谢。

**Comment by JamesChenGithub** [comment]
贴下crash的堆栈信息

**Comment by hnzlk2014** [comment]
按照上面的操作步骤，随心播必现啊

**Comment by hnzlk2014** [comment]
![image](https://cloud.githubusercontent.com/assets/6149516/18239786/1c0e60d6-737a-11e6-9098-19d4cde056f5.png)

**Comment by JamesChenGithub** [comment]
check下最新代码，已修复，原因是：结束直播时，退后台，再进的时候，界面上的定时器又重新开起来导致的
