### ISSUE TITLE
请问今天的 commit 修复了什么 Bugs？

### ISSUE THREAD

**Issue by iTofu** [zhaoyang21cn/iOS_Suixinbo#56]
这一个 [Commit](https://github.com/zhaoyang21cn/iOS_Suixinbo/commit/e384ff491ca7b26eb9c6121c97afa70787939a7c)，另外 AVSDK 1.8.2.61 有什么变化？

**Comment by iTofu** [comment]
我尝试把 AVSDK  1.8.2.61 替换掉上一个版本的 SDK 后，开播后大概 1s 画面会闪一下，黑一下立马又正常，只有主播端出现，这可能是什么原因导致的？

**Comment by JamesChenGithub** [comment]
fix界面上的bug 。1.8.2.61 只是修复了外部用户反馈的一些bug，跟你说的这个应该没有关系。你贴一下你的spear配置。

**Comment by iTofu** [comment]
<img width="643" alt="01" src="https://cloud.githubusercontent.com/assets/10044430/19338449/ba0d3878-914f-11e6-89bb-a20f66699581.png">
<img width="645" alt="02" src="https://cloud.githubusercontent.com/assets/10044430/19338451/ba4717f0-914f-11e6-822a-ce07d3c9aa8e.png">

**Comment by iTofu** [comment]
今天再次导一遍又正常了，上次导了好几遍都异常…… 这次跟上次相比，我删除了 Libs 中的 Analytics 库，难道是有关系吗？不过已经好了，就不去研究了，忙……
