### ISSUE TITLE
xplatform.framework/xplatform(md5.o) 和环信冲突

### ISSUE THREAD

**Issue by MrWilsonXu** [zhaoyang21cn/iOS_Suixinbo#58]
![2016-11-24 6 31 21](https://cloud.githubusercontent.com/assets/13956449/20595280/4ada8cda-b274-11e6-8ac9-5791891b70ec.png)
这个和环信冲突怎么解决

**Comment by JamesChenGithub** [comment]
已提工单解决，后续解决了在这里通知

**Comment by JamesChenGithub** [comment]
SDK在185版本中修复了，建议届时等185更新

**Comment by MrWilsonXu** [comment]
谢谢啦
