### ISSUE TITLE
登录的方法在哪里？是否有代码可以调用？

### ISSUE THREAD

**Issue by fujin121** [zhaoyang21cn/iOS_Suixinbo#59]
demo里的登录界面，登录时调用的方法找不到呀！登录的方法和登录界面绑定了！！
_tlsuiwx = TLSUILogin(self, setting); 
请问，登录和注册有没有别的方法，可以自己用代码调用。

**Comment by wilderliao1** [comment]
可以在TLSSDK里面找到登录注册等方法。demo里面的登录注册和界面绑定了，看不到。
