### ISSUE TITLE
开启直播3秒左右后必定黑屏并且卡顿闪一下

### ISSUE THREAD

**Issue by hellerchen** [zhaoyang21cn/iOS_Suixinbo#6]
设备:iPhoneSE,iPhone6s,iPhone6s plus iOS 9.1~9.3
SDK:1.8.1
问题:当画面开始显示起算,3秒左右后必定黑屏并且卡顿闪一下,1.7没有这个问题,感觉像是画面对焦了一下

**Comment by zhaoyang21cn** [comment]
1.8及1.8.1我们着重优化了进入房间的速度，采用缓存I帧的方式进行，会在一定程度上进入房间后出现一次帧跳变，但是进入后立即会看到视频帧，从用户体验上来说是更优的

**Comment by hellerchen** [comment]
@zhaoyang21cn 你好,.1.8.1进入房间的速度确实是提高了很多,但是对比一些直播平台,例如映客,在直播之类的,并没有太大的速度优势,并且他们不会出现我描述的问题,难道他们没用你说的帧跳变,但是却又做得比你们好?

**Comment by JamesChenGithub** [comment]
闪屏问题原因：云后端使用的配置与本地默认配置不一样（主要是分辨率以及帧率），SDK底层会重启摄像头导致，现将云端配置改到640*480, 15fps ， 验证不出现。已跟SDK同事反馈该问题，后期会修复，敬请关注相关的git消息

**Comment by hellerchen** [comment]
@JamesChenGithub 感谢回复
