### ISSUE TITLE
iTunes Connect 审核总是出问题

### ISSUE THREAD

**Issue by 1xiaocainiao** [zhaoyang21cn/iOS_Suixinbo#61]
我们用的版本，提交APPStroe审核总是在ipv6 的时候出现问题，导致审核不通过
We discovered one or more bugs in your app when reviewed on iPhone running iOS 10.2.1 on Wi-Fi connected to an IPv6 network.
具体表现为有时候发送自定义消息，别人收不到，或者新建直播的时候由于延迟过高导致经常新建直播失败,请问是支持ipv6有问题还是什么原因呢

**Comment by JamesChenGithub** [comment]
用的SDK版本是多少？

**Comment by JamesChenGithub** [comment]
是否有更新过最过的xplatform.framework

**Comment by 1xiaocainiao** [comment]
抱歉这么晚才看到回复，我用的应该是1.8.2一下版本，当时是没有xplatform.framework这个库文件的，该怎么办呢，方便详细指导一下吗

**Comment by JamesChenGithub** [comment]
建议更新一下SDK版本，182 ipv6下访问的问题，后来更新的

**Comment by 1xiaocainiao** [comment]
好的，谢谢
