### ISSUE TITLE
重新进入直播间，context都会重新创建

### ISSUE THREAD

**Issue by jming0618** [zhaoyang21cn/iOS_Suixinbo#7]
随心播Demo
#if kIsUseAVSDKAsLiveScene
        QAVContext *context = [TCAVSharedContext sharedContext];
        if (context)
        {
            _avContext = context;
            _isUseSharedContext = YES;
        }
        else
#endif
        {
            QAVContextConfig *config = [[QAVContextConfig alloc] init];
            
            NSString *appid = [host imSDKAppId];
            
            config.sdk_app_id = appid;
            config.app_id_at3rd = appid;
            config.identifier = [host imUserId];
            config.account_type = [host imSDKAccountType];
            _avContext = [QAVContext CreateContext:config];
        }
kIsUseAVSDKAsLiveScene为1，发现还是会每次创建_avContext。
在TCAVSharedContext类里发现有处错误：
+ (void)configWithStartedContext:(QAVContext *)context
{
    if (!context && !isQAVContextInitSucc)
    {
        TCAVIMLog(@"配置Context");
        isQAVContextInitSucc = YES;
        kSharedConext = context;
    }
}

 if (!context && !isQAVContextInitSucc) ? 这条件语句判断有误吧。。

还有TCAVBaseRoomEngine里的
#if kIsUseAVSDKAsLiveScene
        // 配置共享的context
        if (_isUseSharedContext)
        {
            [TCAVSharedContext configWithStartedContext:_avContext];
        }
#endif
这里逻辑有问题，_isUseSharedContext会在获取到上次的context才会为YES，所有这里不会执行

**Comment by JamesChenGithub** [comment]
已更新，并添加登录时，创建QAVContext，优化首次进房速度
